### ISSUE TITLE
Support for Federaton 2.5 and 2.6

### ISSUE THREAD

**Issue by RoKKim** [apollographql/apollo-federation-subgraph-compatibility#595] opened 2024-01-31 14:46 UTC
Is there a timeline for the release of tests for `@authenticated`, `@requiresScopes`, and `@policy` directives from Federation versions 2.5 and 2.6?

**Comment by dariuszkuc** [comment] 2024-02-06 00:25
TLDR those are enterprise only features and sadly we currently don't have an easy way to test those out (without requiring users to sign up for enterprise trial).

Closing as duplicate of https://github.com/apollographql/apollo-federation-subgraph-compatibility/issues/469

**Closed by dariuszkuc** 2024-02-06 00:25 UTC
